Olimp2
Caraul/Olimpics pull request #4
Opened 2019-12-14 16:13 UTC by Bobafett89

2019-12-16 13:12 UTC, Caraul commented on Olimp2/Olimp2/Program.cs
> +        static public int DayInMonth(int nyear)
https://docs.microsoft.com/ru-ru/dotnet/api/system.datetime.daysinmonth?view=netcore-3.0

2019-12-16 13:13 UTC, Caraul commented on Olimp2/Olimp2/Program.cs
> +        static public void prog(int year, int NumberOfBonusWeekend)
Функции должны возвращать значения

2019-12-16 13:13 UTC, Caraul commented on Olimp2/Olimp2.sln
> +﻿
А зачем нам еще один .sln? У нас уже есть, давай в него и собирать решения.

2019-12-16 13:18 UTC, Caraul commented on Olimp2/Olimp2/Program.cs
> +        static public void FirstDayOfYear(int nyear)
https://docs.microsoft.com/ru-ru/dotnet/api/system.datetimeoffset.dayofweek?view=netcore-3.0

2019-12-16 13:19 UTC, Caraul commented on Olimp2/Olimp2/Program.cs
> +        static public int dw, month, dm, wkday, wkend; // DayOfWeek, DayOfMonth, weekday, weekend
// DayOfWeek, DayOfMonth, weekday, weekend - а почему бы переменные так и не назвать?

2019-12-16 13:21 UTC, Caraul requested changes
В целом - очень хорошо.
В деталях еще надо поработать.

2019-12-19 20:35 UTC, Bobafett89 commented
не сделал тесты поскольку мне после школы стало плохо и какое-то время в постели пролежал и из-за этого не успел

2019-12-20 09:28 UTC, Caraul commented
Вот поэтому и не нужно откладывать на последний момент - может произойти
что-то непредвиденное. что помешает планам.

чт, 19 дек. 2019 г. в 23:35, Bobafett89 <notifications@github.com>:

> не сделал тесты поскольку мне после школы стало плохо и какое-то время в
> постели пролежал и из-за этого не успел
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Caraul/Olimpics/pull/4?email_source=notifications&email_token=ABPJSRFJRPNU3AZL5KWIFPTQZPLJ3A5CNFSM4J23LGWKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHK3FFI#issuecomment-567653013>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABPJSRANWVGR3M34RON52S3QZPLJ3ANCNFSM4J23LGWA>
> .
>

2019-12-20 09:48 UTC, Caraul commented
Почитай пока вот это

https://ravesli.com/urok-50-pochemu-globalnye-peremennye-zlo/
https://ru.wikipedia.org/wiki/%D0%A7%D0%B8%D1%81%D1%82%D0%BE%D1%82%D0%B0_%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8

https://ru.hexlet.io/courses/introduction_to_programming/lessons/pure/theory_unit


А на выходных обсудим алгоритм. И тесты не забудь доделать.


пт, 20 дек. 2019 г. в 12:28, Семья Алексеевых <alenalexa@gmail.com>:

> Вот поэтому и не нужно откладывать на последний момент - может произойти
> что-то непредвиденное. что помешает планам.
>
> чт, 19 дек. 2019 г. в 23:35, Bobafett89 <notifications@github.com>:
>
>> не сделал тесты поскольку мне после школы стало плохо и какое-то время в
>> постели пролежал и из-за этого не успел
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Caraul/Olimpics/pull/4?email_source=notifications&email_token=ABPJSRFJRPNU3AZL5KWIFPTQZPLJ3A5CNFSM4J23LGWKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHK3FFI#issuecomment-567653013>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ABPJSRANWVGR3M34RON52S3QZPLJ3ANCNFSM4J23LGWA>
>> .
>>
>

2019-12-22 17:54 UTC, merged