NewClasses
Caraul/Olimpics pull request #7
Opened 2020-01-25 13:57 UTC by Bobafett89

2020-01-27 10:03 UTC, Caraul commented on Olimp/Labirint/Tunnel.cs
> +        public bool IsHaveExit = false;
IsHaveExit -> HasExit

2020-01-27 10:05 UTC, Caraul commented on Olimp/Labirint/Tunnel.cs
> +        public bool IsHaveExit = false;
Публичные свойства должны быть property
https://softwareengineering.stackexchange.com/questions/161303/is-it-bad-practice-to-use-public-fields

2020-01-27 10:07 UTC, Caraul commented on Olimp/Labirint/Room1.cs
> +        public int[] WalkedThrough(int[] variables)
А тут надо возвращать variables? Они же изменяются прямо в массиве.

2020-01-27 10:12 UTC, Caraul requested changes
Тут исправлений немного

2020-01-29 10:47 UTC, Bobafett89 commented on Olimp/Labirint/Room1.cs
> +        public int[] WalkedThrough(int[] variables)
здесь я не очень понял. Кто они?

2020-01-29 11:43 UTC, Caraul commented on Olimp/Labirint/Room1.cs
> +        public int[] WalkedThrough(int[] variables)
они - это variables. Они изменяются прямо в методе - зачем их же возвращать?

2020-01-29 11:43 UTC, Caraul requested changes
Жду исправлений

2020-01-29 12:02 UTC, Bobafett89 commented on Olimp/Labirint/Room1.cs
> +        public int[] WalkedThrough(int[] variables)
Ну так изменяются те variables что подаются в метод, в классe room1 нету массива variables

2020-01-29 12:55 UTC, Caraul commented on Olimp/Labirint/Room1.cs
> +        public int[] WalkedThrough(int[] variables)
Верно. Но они подаются снаружи - значит, про них знает вызывающий.
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/reference-types
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/passing-reference-type-parameters
Array - это reference type или value type?

2020-01-29 14:06 UTC, Caraul requested changes
Осталось одно - **_все_** публичные свойства должны быть property

2020-01-29 14:51 UTC, Caraul commented on Olimp/Labirint/Tunnel.cs
> +        public bool HasExit { get { return HasExit; } set { HasExit = value; } }
Это неправильно - { get; set; } было правильно

2020-01-29 14:52 UTC, Caraul commented on Olimp/Labirint/Map.cs
> +                if (index <= descriptionOfMapArray[3] && index != 0)
Здесь проще будет tunnels[index].HasExit = ...
В if как раз вычисляется bool

2020-01-29 14:53 UTC, Caraul requested changes
Что-то пошло не в ту сторону

2020-01-29 15:09 UTC, Bobafett89 commented on Olimp/Labirint/Tunnel.cs
> +        public bool IsHaveExit = false;
"все публичные свойства должны быть property" не понял

2020-01-29 17:58 UTC, Caraul commented on Olimp/Labirint/Tunnel.cs
> +        public bool IsHaveExit = false;
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/fields
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/properties

2020-01-29 18:03 UTC, Bobafett89 commented on Olimp/Labirint/Tunnel.cs
> +        public bool IsHaveExit = false;
всё равно не понял

2020-01-29 20:41 UTC, Caraul commented on Olimp/Labirint/Tunnel.cs
> +        public bool IsHaveExit = false;
А разницу между полем и свойством понял?

2020-01-31 12:41 UTC, merged